logging:
  config: classpath:logback-spring.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
#  mvc:
#    view:
#      prefix: /WEB-INF/html/
#      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/page/
    suffix: .html
    encoding: utf-8
    mode: LEGACYHTML5
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.my.logdemo

